image: mcr.microsoft.com/dotnet/sdk:latest

before_script:
  - 'dotnet restore'

build:
  stage: build
  script:
  - 'dotnet build --no-restore'

test:
  stage: test
  script:
  - 'dotnet test --no-build'

# deploy:
#   stage: deploy
#   script:
#   - ''
